language: java

jdk:
  - oraclejdk7

#install: 
#   - echo -e "building jbake snapshot from repository\n"
#    - git clone -b feature/newEngines https://github.com/Vad1mo/JBake.git
#    - mvn -q -f ./jbake/pom.xml install -DskipTests
#    - rm -rf jbake

#before_script: mvn versions:set -DnewVersion=1.0.1

script:
  - mvn -q clean
  - mvn -q initialize
  - mvn -q package
  - mvn -X site

# after_success: mvn versions:set -DnewVersion=1.0.2-SNAPSHOT

env:
  global:
    secure: bQkAdCXe8nFe/btTAjcCRgCg+9QOmO/nUc7GmCjltKinLnx7azFg4vWTeUEvUiSeMw3lAXp0WlVuxSG35ZSUIjnFNgMMcue3YceTIxOikKaFeQL9C/aJLe+EY0DUuK4cHMO1EvV4TJwOUNsk4IZxEYSXhsxHTIIyyWhL2+HtZYo=
